# Generated by Django 6.0.2 on 2026-02-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0002_crowdstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrowdData',
        ),
    ]
